version: "3"

services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: Fatima
      POSTGRES_USER: postgres
      POSTGRES_DB: employee_dbb
    ports:
      - 5432:5432      
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: m.amine@giantlink.ma
      PGADMIN_DEFAULT_PASSWORD: 123456789
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
